---
######## API ########
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-staging-config
  namespace: default
  labels:
    env: staging
    app: api-staging
data:
  NODE_ENV: staging
  MONGODB_HOST: ---
  MONGODB_DATABASE: ---
  JWT_SECRET: ---
  PORT: "80"
---
######## CLIENT ########
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-staging-config
  namespace: default
  labels:
    env: staging
    app: client-staging
data:
  NODE_ENV: staging
---
