---
######## API ########
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: default
  labels:
    env: production
    app: api
data:
  NODE_ENV: production
  MONGODB_HOST: ---
  MONGODB_DATABASE: ---
  JWT_SECRET: ---
  PORT: "80"
---
######## CLIENT ########
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: default
  labels:
    env: production
    app: client
data:
  NODE_ENV: production
---
