env:
  browser: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules:
  indent: ['error', 2, { 'SwitchCase': 1 }]
  semi: ['error', 'never']
  quotes: ['error', 'single']
  no-underscore-dangle: ['off']
  import/prefer-default-export: ['off']
  import/named: ['off']
  import/no-named-as-default: ['off']
  import/no-named-as-default-member: ['off']
  space-before-function-paren: ['error', 'always']
